Repository littlefs-project/littlefs, pull requests merged in 2020-12, with the labels that each got.

#412 Added littlefs-python to the related projects section
  README.md
Labels: next patch, v2.3

#486 Fix assert
  bd/lfs_testbd.c
Labels: next patch, v2.3

#487 Fix several wear-leveling issues found in lfs_alloc_reset
  lfs.c
  scripts/readtree.py
Labels: next patch, v2.3, wear leveling

#395 lfs_bd_cmp() compares more bytes at one time
  lfs.c
Labels: next minor, performance, v2.3

#490 Fix allocation-eviction issue when erase state is multiple of block_cycles+1
  lfs.c
Labels: next patch, v2.3

#495 Minor release: v2.3
  .travis.yml
  README.md
  bd/lfs_testbd.c
  lfs.c
  lfs.h
  scripts/readtree.py
Labels: v2.3
