Repository littlefs-project/littlefs, pull requests merged in 2020-03, with the labels that each got.

#401 Lookahead corruption fix given an IO Error during traversal
  lfs.c
  tests/test_alloc.toml
Labels: needs test, needs work, next patch, v2.2

#266 Revert "Don't bypass cache in `lfs_cache_prog()` and `lfs_cache_read()`"
  lfs.c
Labels: next minor, v2.2

#322 Allow debug prints without __VA_ARGS__ in non-MSVC
  lfs_util.h
Labels: next minor, v2.2

#356 Update SPEC.md
  SPEC.md
Labels: next patch, v2.2

#360 Fix incorrect comment on `lfs_npw2`
  lfs_util.h
Labels: next patch, v2.2

#373 Indicate C99 standard as target for LittleFS code
  README.md
Labels: next patch, v2.2

#372 Rework test framework, fix a number of related bugs
  .gitignore
  .travis.yml
  Makefile
  bd/lfs_filebd.c
  bd/lfs_filebd.h
  bd/lfs_rambd.c
  bd/lfs_rambd.h
  bd/lfs_testbd.c
  bd/lfs_testbd.h
  emubd/lfs_emubd.c
  emubd/lfs_emubd.h
  lfs.c
  lfs.h
  lfs_util.h
  scripts/corrupt.py
  scripts/debug.py
  scripts/explode_asserts.py
  scripts/readblock.py
  scripts/readmdir.py
  scripts/readtree.py
  scripts/results.py
  scripts/template.fmt
  scripts/test.py
  tests/test_alloc.toml
  tests/test_attrs.toml
  tests/test_badblocks.toml
  tests/test_corrupt.sh
  tests/test_dirs.sh
  tests/test_dirs.toml
  tests/test_entries.sh
  tests/test_entries.toml
  tests/test_evil.toml
  tests/test_exhaustion.toml
  tests/test_files.sh
  tests/test_files.toml
  tests/test_format.sh
  tests/test_interspersed.sh
  tests/test_interspersed.toml
  tests/test_move.sh
  tests/test_move.toml
  tests/test_orphan.sh
  tests/test_orphans.toml
  tests/test_paths.sh
  tests/test_paths.toml
  tests/test_relocations.sh
  tests/test_relocations.toml
  tests/test_seek.sh
  tests/test_seek.toml
  tests/test_superblocks.toml
  tests/test_truncate.sh
  tests/test_truncate.toml
Labels: next minor, v2.2
