Repository littlefs-project/littlefs, pull requests merged in 2021-01, with the labels that each got.

#499 Moved lfs_mdir_isopen behind LFS_NO_ASSERT
  lfs.c
Labels: next patch, v2.4

#501 Fixed incorrect documentation in test.py
  scripts/test.py
Labels: documentation, next patch, v2.4

#502 Add metadata_max config to help performance on devices with large blocks
  lfs.c
  lfs.h
Labels: next minor, v2.4

#508 Moved sanity check in lfs_format after compaction
  lfs.c
Labels: next patch, v2.4

#511 Skip flushing file if lfs_file_rawseek() doesn't change position
  lfs.c
  tests/test_truncate.toml
Labels: next minor, v2.4

#516 Adopt GitHub Actions, bring in a number of script/Makefile improvements
  .github/workflows/post-release.yml
  .github/workflows/release.yml
  .github/workflows/status.yml
  .github/workflows/test.yml
  .travis.yml
  Makefile
  lfs.c
  lfs_util.h
  scripts/code.py
  scripts/coverage.py
  scripts/test.py
Labels: next minor, v2.4

#519 Minor release: v2.4
  .github/workflows/post-release.yml
  .github/workflows/release.yml
  .github/workflows/status.yml
  .github/workflows/test.yml
  .travis.yml
  Makefile
  lfs.c
  lfs.h
  lfs_util.h
  scripts/code.py
  scripts/coverage.py
  scripts/test.py
  tests/test_truncate.toml
Labels: v2.4
