Repository littlefs-project/littlefs, pull requests merged in 2022-04, with the labels that each got.

#584 Fail mount when the block size changes
  lfs.c
Labels: enhancement, next minor, v2.5

#614 don't use lfs_file_open() when LFS_NO_MALLOC is set
  lfs.c
  lfs.h
Labels: next minor, v2.5

#630 add the limit, the cursor cannot be set to a negative number
  lfs.c
Labels: enhancement, next minor, v2.5

#632 Fix lfs_file_rawseek performance issue
  lfs.c
Labels: performance, next minor, v2.5

#638 Removed invalid overwrite for return value.
  lfs.c
Labels: next minor, v2.5

#657 Update copyright notice
  LICENSE.md
  bd/lfs_filebd.c
  bd/lfs_filebd.h
  bd/lfs_rambd.c
  bd/lfs_rambd.h
  bd/lfs_testbd.c
  bd/lfs_testbd.h
  lfs.c
  lfs.h
  lfs_util.c
  lfs_util.h
Labels: next minor, v2.5

#666 Optimization of the rename case.
  lfs.c
Labels: performance, next minor, v2.5
