Repository littlefs-project/littlefs, pull requests merged in 2022-11, with the labels that each got.

#673 Fix readme Mbed link
  README.md
Labels: next patch, documentation

#675 Fix unused function warning with LFS_NO_MALLOC
  lfs.c
Labels: next patch, lint

#715 lfs_filebd_sync: fix compilation on Windows
  bd/lfs_filebd.c
Labels: next patch

#724 Fix self-assign warnings discovered by clang, remove some warning flags
  .github/workflows/test.yml
  Makefile
  lfs.c
Labels: next patch, lint

#726 Improve lfs_file_close usage description
  lfs.h
Labels: next patch, documentation

#740 Fix invalid block size reporting.
  lfs.c
Labels: next patch
