Repository littlefs-project/littlefs, pull requests merged in 2023-04, with the labels that each got.

#497 Forward-looking erase-state CRCs
  .github/workflows/test.yml
  Makefile
  SPEC.md
  bd/lfs_emubd.c
  lfs.c
  lfs.h
  scripts/changeprefix.py
  scripts/readmdir.py
  tests/test_compat.toml
  tests/test_powerloss.toml
Labels: enhancement, next minor

#809 Adopt Brent's algorithm for cycle detection
  lfs.c
Labels: enhancement, next minor

#572 Add littlefs-disk-img-viewer to README
  README.md
Labels: next patch

#718 Add "chamelon" to the related projects section.
  README.md
Labels: next patch

#807 Add littlefs2 crate to README
  README.md
Labels: next patch, documentation

#801 Add an assert for truthy-preserving bool conversions
  lfs.c
Labels: enhancement, next minor

#802 Add explicit assert for minimum block size of 128 bytes
  lfs.c
Labels: enhancement, next minor

#800 Fix block-boundary truncate issues
  lfs.c
  tests/test_truncate.toml
Labels: enhancement, next minor

#805 Fix issue where seeking to end-of-directory return LFS_ERR_INVAL
  lfs.c
  tests/test_dirs.toml
Labels: next minor
