Repository littlefs-project/littlefs, pull requests merged in 2023-12, with the labels that each got.

#898 Update DESIGN.md minor typo
  DESIGN.md
Labels: next patch, documentation

#910 Increase threshold for superblock expansion from ~50% -> ~88% full
  lfs.c
Labels: next patch, wear leveling

#911 Fix struct sizes missing from generated release notes
  .github/workflows/release.yml
Labels: next patch
