Repository littlefs-project/littlefs, pull requests merged in 2023-09, with the labels that each got.

#849 Fix release script breaking if there is no previous version
  .github/workflows/release.yml
Labels: next patch

#855 initlize struct lfs_diskoff disk = {0}
  lfs.c
Labels: next patch, lint

#863 Fix integer conversion warning from Code Composer Studio
  lfs.c
Labels: next patch, lint

#866 Infer block_count from superblock if not provided in config.
  bd/lfs_emubd.c
  bd/lfs_emubd.h
  bd/lfs_filebd.c
  bd/lfs_filebd.h
  bd/lfs_rambd.c
  bd/lfs_rambd.h
  lfs.c
  lfs.h
  runners/bench_runner.c
  runners/bench_runner.h
  runners/test_runner.c
  runners/test_runner.h
  tests/test_alloc.toml
  tests/test_badblocks.toml
  tests/test_exhaustion.toml
  tests/test_superblocks.toml
Labels: enhancement, next minor

#875 Add lfs_fs_gc to enable proactive finding of free blocks
  lfs.c
  lfs.h
  tests/test_alloc.toml
Labels: enhancement, next minor
