Repository littlefs-project/littlefs, pull requests merged in 2023-05, with the labels that each got.

#811 Fix issue where lfs_fs_deorphan may run more than needed
  lfs.c
  tests/test_orphans.toml
Labels: next patch

#812 Add lfs_fs_mkconsistent
  lfs.c
  lfs.h
  tests/test_orphans.toml
Labels: enhancement, next minor

#766 Add test scenario for truncating to a block size
  tests/test_truncate.toml
Labels: fixed?, needs fix

#786 Add missing iterations in tests
  tests/test_dirs.toml
Labels: needs investigation, fixed?

#818 Convince GitHub littlefs is a C project
  .gitattributes
Labels: next patch, github

#819 Fix build for AVR
  lfs.c
Labels: next patch

#832 Remove unnecessary sys/types.h include
  lfs_util.h
Labels: next patch
