Repository littlefs-project/littlefs, pull requests merged in 2024-12, with the labels that each got.

#1013 Write the detect cycles function as a function to optimize code
  lfs.c
Labels: next minor, code size

#997 Fix some more LFS_TRACE format specifiers
  lfs.c
Labels: next patch, lint

#1027 Fix seek undefined behavior on signed integer overflow
  lfs.c
  tests/test_seek.toml
Labels: next patch

#1031 Fix metadata_max==prog_size commit->end calculation
  lfs.c
  runners/bench_runner.c
  runners/bench_runner.h
  runners/test_runner.c
  runners/test_runner.h
  tests/test_superblocks.toml
Labels: next patch, metadata limits

#1038 Add links to ramcrc32bd and ramrsbd
  README.md
Labels: next patch, documentation

#1046 paths: Revisit path parsing, fix trailing slash behavior
  lfs.c
  tests/test_paths.toml
Labels: enhancement, next minor, api tweak

#1053 gha: Fix x86-only statuses
  .github/workflows/test.yml
Labels: next patch, ci

#1052 Assert on NULL IO functions
  lfs.c
  scripts/prettyasserts.py
Labels: enhancement
