Repository littlefs-project/littlefs, pull requests merged in 2024-01, with the labels that each got.

#886 Add value-range checks for user-definable macros at compile-time
  lfs.c
  lfs.h
Labels: enhancement, next minor

#909 Add some easier util overrides: LFS_MALLOC/FREE/CRC
  lfs_util.c
  lfs_util.h
Labels: enhancement, next minor

#912 Relaxed lookahead alignment, other internal block alloc readability improvements
  lfs.c
  lfs.h
  lfs_util.h
  tests/test_orphans.toml
Labels: enhancement, next minor

#916 Change CI to just run on ubuntu-latest
  .github/workflows/post-release.yml
  .github/workflows/release.yml
  .github/workflows/status.yml
  .github/workflows/test.yml
Labels: next minor, ci

#917 Fix return value of lfs_rename()
  lfs.c
  tests/test_dirs.toml
Labels: enhancement, next minor

#915 Rename internal functions _raw* -> _*_
  bd/lfs_emubd.c
  lfs.c
Labels: next minor, documentation
